using System;
using System.Collections.Generic;
using OpenSwos.Assets;

namespace OpenSwos.Competition.Career;

/// <summary>
/// Creates the deterministic yearly youth intake and keeps the free-agent
/// market bounded. This uses its own CareerRng streams and never advances the
/// competition match/draw RNG state.
/// </summary>
public static class RegenModel
{
    private const int SquadTarget = 16;
    private const int SquadCap = 18;
    private const int FreeAgentCap = 300;

    /// <summary>
    /// Runs one club intake per club, adds a small global intake, then removes
    /// the oldest and weakest surplus free agents. Clubs are visited in global
    /// id order so equivalent worlds always produce equivalent intakes.
    /// </summary>
    public static void RunRegen(CareerWorld world)
    {
        if (world is null) throw new ArgumentNullException(nameof(world));

        List<ushort> clubIds = new(world.Clubs.Keys);
        clubIds.Sort();

        // World-wide names already carried by living GENERATED players. A new
        // youth's name is checked against these, so subsequent intakes stay
        // unique against everything created in earlier seasons too.
        UsedNames used = CollectGeneratedNames(world);

        foreach (ushort clubId in clubIds)
        {
            CareerClub club = world.Clubs[clubId];
            MoveSquadSurplusToFreeAgents(club, world.FreeAgents);

            // First repair retirement holes through the desired core of 16.
            // A club at or below that mark may then receive one new intake
            // player, settling normal squads at 17 rather than growing forever.
            int youthCount = Math.Max(0, SquadTarget - club.Squad.Count);
            if (club.Squad.Count <= SquadTarget)
                youthCount++;
            for (int i = 0; i < youthCount; i++)
            {
                CareerPlayer youth = GenerateYouth(world, clubId, NextYouthSeed(world), used);
                if (club.Squad.Count < SquadCap)
                {
                    club.Squad.Add(youth);
                }
                else
                {
                    youth.ClubId = 0;
                    world.FreeAgents.Add(youth);
                }
            }
        }

        // A small independent intake means the market remains useful even if
        // every club happens to retain a full squad.
        int freeAgentIntake = Math.Max(1, (clubIds.Count + 7) / 8);
        for (int i = 0; i < freeAgentIntake; i++)
            world.FreeAgents.Add(GenerateYouth(world, 0, NextYouthSeed(world), used));

        PruneFreeAgents(world.FreeAgents);
    }

    // Tracks the names already carried by living generated players, so a fresh
    // intake can be checked for world-wide uniqueness. Two levels are kept:
    //  * Surnames — preferred: a new youth avoids any surname already in use.
    //  * Full "FIRST SURNAME" strings — the hard guarantee: once the roster's
    //    distinct surnames are exhausted (there are more generated players than
    //    distinct surnames), a surname must be reused, and the full name is kept
    //    unique instead by pairing it with an unused first name.
    // Real TEAM.* players are excluded: they may legitimately share a name.
    private sealed class UsedNames
    {
        public readonly HashSet<string> Surnames = new(StringComparer.OrdinalIgnoreCase);
        public readonly HashSet<string> FullNames = new(StringComparer.OrdinalIgnoreCase);
    }

    private static UsedNames CollectGeneratedNames(CareerWorld world)
    {
        UsedNames used = new();
        foreach (CareerClub club in world.Clubs.Values)
            foreach (CareerPlayer player in club.Squad)
                AddIfGenerated(used, player);
        foreach (CareerPlayer player in world.FreeAgents)
            AddIfGenerated(used, player);
        return used;
    }

    private static void AddIfGenerated(UsedNames used, CareerPlayer player)
    {
        if (player is null || !player.Generated || player.Retired) return;
        string full = (player.Name ?? "").Trim();
        if (full.Length == 0) return;
        used.FullNames.Add(full);
        string surname = SurnameOf(full);
        if (surname.Length > 0) used.Surnames.Add(surname);
    }

    private static string SurnameOf(string? name)
    {
        if (string.IsNullOrWhiteSpace(name)) return string.Empty;
        string trimmed = name.Trim();
        int separator = trimmed.LastIndexOf(' ');
        return separator < 0 ? trimmed : trimmed[(separator + 1)..];
    }

    /// <summary>
    /// Creates one complete 16--18-year-old player. The supplied seed is a
    /// per-player seed generated by <see cref="RunRegen"/>; the player id is
    /// also part of every CareerRng stream used here.
    /// </summary>
    public static CareerPlayer GenerateYouth(CareerWorld world, ushort clubId, uint seed)
        => GenerateYouth(world, clubId, seed, CollectGeneratedNames(world
            ?? throw new ArgumentNullException(nameof(world))));

    /// <summary>
    /// As <see cref="GenerateYouth(CareerWorld, ushort, uint)"/> but threads the
    /// caller's live set of already-used generated names so a whole intake run
    /// stays unique. The chosen name is added to <paramref name="used"/> before
    /// returning.
    /// </summary>
    private static CareerPlayer GenerateYouth(CareerWorld world, ushort clubId, uint seed, UsedNames used)
    {
        if (world is null) throw new ArgumentNullException(nameof(world));
        if (used is null) throw new ArgumentNullException(nameof(used));

        int id = world.NextPlayerId++;
        CareerRng rng = new(seed ^ unchecked((uint)world.Season), id);
        byte nationality = NationalityFor(world, clubId, ref rng);
        CareerClub? club = clubId != 0 && world.Clubs.TryGetValue(clubId, out CareerClub? foundClub)
            ? foundClub
            : null;
        string position = PickPosition(club, ref rng);

        CareerPlayer youth = new()
        {
            Id = id,
            ClubId = clubId,
            Name = PickYouthName(world, nationality, used, ref rng),
            Generated = true,
            Position = position,
            Nationality = nationality,
            ShirtNumber = (byte)rng.Range(1, 99),
            Face = rng.NextInt(3),
            Age = rng.Range(16, 18),
        };

        AssignStartingSkills(youth, position, ref rng);

        // Use a new deterministic seed for the existing attribute models;
        // they additionally key their streams to the new stable player id.
        uint attributeSeed = rng.NextU();
        StaminaModel.AssignStamina(youth, attributeSeed);
        PotentialModel.AssignPotential(youth, attributeSeed);
        return youth;
    }

    private static uint NextYouthSeed(CareerWorld world)
    {
        CareerRng rng = new(unchecked((uint)world.Season) ^ 0xB5297A4Du, world.NextPlayerId);
        return rng.NextU();
    }

    private static byte NationalityFor(CareerWorld world, ushort clubId, ref CareerRng rng)
    {
        if (clubId != 0 && world.Clubs.TryGetValue(clubId, out CareerClub? club))
        {
            Dictionary<byte, int> counts = new();
            foreach (CareerPlayer player in club.Squad)
            {
                if (!IsUsableNationality(player.Nationality)) continue;
                counts.TryGetValue(player.Nationality, out int count);
                counts[player.Nationality] = count + 1;
            }

            byte chosen = 0;
            int mostCommon = -1;
            foreach (KeyValuePair<byte, int> entry in counts)
            {
                if (entry.Value > mostCommon
                    || (entry.Value == mostCommon && entry.Key < chosen))
                {
                    chosen = entry.Key;
                    mostCommon = entry.Value;
                }
            }
            if (mostCommon >= 0) return chosen;
        }

        List<byte> nations = new();
        for (int nation = 0; nation < PlayerNationNames.CustomIndex; nation++)
            if (IsUsableNationality((byte)nation)) nations.Add((byte)nation);
        return nations.Count > 0 ? nations[rng.NextInt(nations.Count)] : (byte)0;
    }

    // Player nationality byte uses the PLAYER-nation numbering (0=ALB..152=CUS).
    // Every real nation 0..151 is usable; only the custom-team slot is excluded.
    private static bool IsUsableNationality(byte nationality)
    {
        return nationality < PlayerNationNames.CustomIndex;
    }

    // A generated youth is ALWAYS "FIRST SURNAME" (two real tokens, never a bare
    // nickname). Uniqueness is enforced in two tiers, both suffix-free:
    //  1. Prefer a surname no living generated player carries (own nationality,
    //     then continent, then global pool) — this alone makes the full name unique.
    //  2. Only once every distinct surname is taken (more generated players than
    //     distinct surnames), reuse a surname but pick a first name that keeps the
    //     full "FIRST SURNAME" pair unique.
    // The chosen full name is recorded in `used` before returning.
    private static string PickYouthName(
        CareerWorld world, byte nationality, UsedNames used, ref CareerRng rng)
    {
        List<string> surnames = CollectTokens(world.YouthSurnamePools, nationality, sameContinentOnly: false, ownOnly: true);
        string? surname = PickUnused(surnames, used.Surnames, ref rng);
        if (surname is null)
        {
            surnames = CollectTokens(world.YouthSurnamePools, nationality, sameContinentOnly: true, ownOnly: false);
            surname = PickUnused(surnames, used.Surnames, ref rng);
        }
        List<string> globalSurnames = CollectTokens(world.YouthSurnamePools, nationality, sameContinentOnly: false, ownOnly: false);
        surname ??= PickUnused(globalSurnames, used.Surnames, ref rng);

        List<string> firstNames = CollectFirstNames(world, nationality);

        string full;
        if (surname is not null)
        {
            // Fresh surname: any first name yields a unique full name.
            string first = firstNames.Count > 0 ? firstNames[rng.NextInt(firstNames.Count)] : "JUNIOR";
            full = first + " " + surname;
        }
        else
        {
            // Every distinct surname is used. Reuse one but pair it with a first
            // name that keeps the full name unique — no numeric suffix.
            surname = globalSurnames.Count > 0
                ? globalSurnames[rng.NextInt(globalSurnames.Count)] : "YOUTH";
            full = BuildUniqueFullName(firstNames, surname, used.FullNames, ref rng);
        }

        used.Surnames.Add(surname);
        used.FullNames.Add(full);
        return full;
    }

    private static List<string> CollectFirstNames(CareerWorld world, byte nationality)
    {
        List<string> pool = CollectTokens(world.YouthFirstNamePools, nationality, sameContinentOnly: false, ownOnly: true);
        if (pool.Count == 0) pool = CollectTokens(world.YouthFirstNamePools, nationality, sameContinentOnly: true, ownOnly: false);
        if (pool.Count == 0) pool = CollectTokens(world.YouthFirstNamePools, nationality, sameContinentOnly: false, ownOnly: false);
        return pool;
    }

    // Deterministic linear probe over the first-name pool for a "FIRST surname"
    // string not already taken. Falls back to a plain pick only if every pairing
    // is somehow used (needs an empty pool or a fully-saturated world).
    private static string BuildUniqueFullName(
        List<string> firstNames, string surname, HashSet<string> usedFullNames, ref CareerRng rng)
    {
        int count = firstNames.Count;
        if (count == 0) return "JUNIOR " + surname;
        int start = rng.NextInt(count);
        for (int i = 0; i < count; i++)
        {
            string candidate = firstNames[(start + i) % count] + " " + surname;
            if (!usedFullNames.Contains(candidate)) return candidate;
        }
        return firstNames[start] + " " + surname;
    }

    // Deterministic linear probe: a random start offset, then the first pool entry
    // (scanning forward, wrapping) not already used. Returns null only when the
    // whole pool is exhausted, letting the caller widen the search.
    private static string? PickUnused(List<string> pool, HashSet<string> used, ref CareerRng rng)
    {
        int count = pool.Count;
        if (count == 0) return null;
        int start = rng.NextInt(count);
        for (int i = 0; i < count; i++)
        {
            string candidate = pool[(start + i) % count];
            if (!used.Contains(candidate)) return candidate;
        }
        return null;
    }

    private static List<string> CollectTokens(
        Dictionary<byte, List<string>> pools, byte nationality, bool sameContinentOnly, bool ownOnly)
    {
        List<string> result = new();
        if (ownOnly)
        {
            if (pools.TryGetValue(nationality, out List<string>? own)) result.AddRange(own);
            return result;
        }

        List<byte> nations = new(pools.Keys);
        nations.Sort();
        int continent = PlayerNationNames.Continent(nationality);
        foreach (byte nation in nations)
        {
            if (sameContinentOnly && PlayerNationNames.Continent(nation) != continent) continue;
            if (pools.TryGetValue(nation, out List<string>? pool))
                result.AddRange(pool);
        }
        return result;
    }

    private static string PickPosition(CareerClub? club, ref CareerRng rng)
    {
        if (club is null)
            return PickFreeAgentPosition(ref rng);

        int keepers = 0, defenders = 0, midfielders = 0, attackers = 0;
        foreach (CareerPlayer player in club.Squad)
        {
            switch (PositionGroup(player.Position))
            {
                case "G": keepers++; break;
                case "D": defenders++; break;
                case "M": midfielders++; break;
                default: attackers++; break;
            }
        }

        // One keeper is the intended 16-player core; a second can already be
        // retained, but youth intake never creates a third. Refill the keeper
        // first if a retirement leaves the squad without one.
        if (keepers == 0) return "G";

        // The remaining 15 slots form a practical D/M/A spread. Pick from the
        // roles with the largest shortage and use CareerRng only to resolve a
        // true tie, keeping equivalent saves deterministic.
        int defenderNeed = 6 - defenders;
        int midfielderNeed = 5 - midfielders;
        int attackerNeed = 4 - attackers;
        int greatestNeed = Math.Max(defenderNeed, Math.Max(midfielderNeed, attackerNeed));
        if (greatestNeed > 0)
        {
            List<string> choices = new(3);
            if (defenderNeed == greatestNeed) choices.Add("D");
            if (midfielderNeed == greatestNeed) choices.Add("M");
            if (attackerNeed == greatestNeed) choices.Add("A");
            return choices[rng.NextInt(choices.Count)];
        }

        // A 17th/18th player is an outfield depth player. Keepers remain at
        // their existing one or two, so the club can never grow a keeper glut.
        return PickOutfieldDepthPosition(ref rng);
    }

    private static string PickFreeAgentPosition(ref CareerRng rng)
    {
        return rng.NextInt(11) switch
        {
            0 => "G",
            <= 4 => "D",
            <= 7 => "M",
            _ => "A",
        };
    }

    private static string PickOutfieldDepthPosition(ref CareerRng rng)
    {
        return rng.NextInt(11) switch
        {
            <= 4 => "D",
            <= 7 => "M",
            _ => "A",
        };
    }

    private static string PositionGroup(string? position)
    {
        string key = position?.Trim().ToUpperInvariant() ?? string.Empty;
        return key switch
        {
            "G" => "G",
            "D" or "RB" or "LB" => "D",
            "M" => "M",
            _ => "A",
        };
    }

    private static void AssignStartingSkills(CareerPlayer youth, string position, ref CareerRng rng)
    {
        if (position == "G")
        {
            // Keep career-generated keepers consistent with TEAM.* records:
            // ability is stored in ValueCode rather than the seven outfield
            // skills. Pick a low youth level and a matching code bucket.
            int level = rng.Range(1, 3);
            youth.ValueCode = Math.Clamp(level * 7 - 3 + rng.NextInt(7), 0, 47);
            youth.Passing = 0;
            youth.Shooting = 0;
            youth.Heading = 0;
            youth.Tackling = 0;
            youth.Control = 0;
            youth.Speed = 0;
            youth.Finishing = 0;
            return;
        }

        youth.Passing = LowSkill(ref rng);
        youth.Shooting = LowSkill(ref rng);
        youth.Heading = LowSkill(ref rng);
        youth.Tackling = LowSkill(ref rng);
        youth.Control = LowSkill(ref rng);
        youth.Speed = LowSkill(ref rng);
        youth.Finishing = LowSkill(ref rng);

        // The skills are all intentionally low (1..3), but the stronger end
        // of that range matches the selected position.
        switch (position)
        {
            case "D":
                youth.Heading = StrongerLowSkill(ref rng);
                youth.Tackling = StrongerLowSkill(ref rng);
                break;
            case "M":
                youth.Passing = StrongerLowSkill(ref rng);
                youth.Control = StrongerLowSkill(ref rng);
                break;
            default: // A
                youth.Shooting = StrongerLowSkill(ref rng);
                youth.Finishing = StrongerLowSkill(ref rng);
                youth.Speed = StrongerLowSkill(ref rng);
                break;
        }

        // Seed the outfield price code from the generated ability so a fresh
        // youth is valued consistently with his starting level (keepers store
        // ability in ValueCode directly and are handled above). A small
        // deterministic jitter keeps equal-skill intakes from looking identical.
        double overall = (youth.Passing + youth.Shooting + youth.Heading + youth.Tackling
            + youth.Control + youth.Speed + youth.Finishing) / 7.0;
        double jitter = (rng.NextDouble() - 0.5) * 2.0;
        youth.ValueCode = System.Math.Clamp(PriceTable.CodeFromOverall(overall) + jitter, 0.0, 60.0);
    }

    private static double LowSkill(ref CareerRng rng) => rng.Range(1, 3);

    private static double StrongerLowSkill(ref CareerRng rng) => rng.Range(2, 3);

    private static void PruneFreeAgents(List<CareerPlayer> freeAgents)
    {
        if (freeAgents.Count <= FreeAgentCap) return;

        freeAgents.Sort(static (left, right) =>
        {
            int byAge = right.Age.CompareTo(left.Age);
            if (byAge != 0) return byAge;

            int byOverall = PotentialModel.OverallOf(left).CompareTo(PotentialModel.OverallOf(right));
            if (byOverall != 0) return byOverall;

            return left.Id.CompareTo(right.Id);
        });
        freeAgents.RemoveRange(0, freeAgents.Count - FreeAgentCap);
    }

    private static void MoveSquadSurplusToFreeAgents(CareerClub club, List<CareerPlayer> freeAgents)
    {
        while (club.Squad.Count > SquadCap)
        {
            int last = club.Squad.Count - 1;
            CareerPlayer surplus = club.Squad[last];
            club.Squad.RemoveAt(last);
            surplus.ClubId = 0;
            freeAgents.Add(surplus);
        }
    }
}
